# Generated by Django 5.2.4 on 2025-07-14 11:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('temperature', models.FloatField()),
                ('description', models.CharField(max_length=200)),
                ('humidity', models.IntegerField()),
                ('wind_speed', models.FloatField()),
            ],
        ),
    ]
